services:
  redis:
    image: redis:6.2.0-alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  backend:
    build:
      context: ddns-backend/
      dockerfile: Dockerfile
    env_file: redis.env
    depends_on:
      - redis
  
  frontend:
    build:
      context: ddns-frontend
      dockerfile: Dockerfile
    env_file: redis.env
    ports: 
      - "5000:8080"
    depends_on:
      - redis
    
  powerdns:
    build:
      context: powerdns/
      dockerfile: Dockerfile
    environment: 
      PDNS_REMOTE_HTTP_HOST: "backend:5000"
    depends_on:
      - backend
